export const style = {
     position: "relative",
     width: "400px",
     height: "100vh",
     display: "flex",
     flexDirection: "column",
     alignItems: "center",
     backgroundColor: "#000",

     div1: {
          borderLeft: "10px solid #fff",
          borderTop: "1px solid #fff",
          borderBottom: "1px solid #fff",
          width: "100px",
          height: "50vh",
          position: "absolute",
          top: "55px",
          left: "50px",
     },
     div2: {
          borderRight: "10px solid #FFF",
          borderTop: "1px solid #FFF",
          borderBottom: "1px solid #FFF",
          width: "100px",
          height: "50vh",
          position: "absolute",

          top: "55px",
          right: "50px",
     },

     head: {
          width: "350px",
          display: "flex",
          height: "50px",
          color: "#fff",
          flexDirection: "row",
          alignItems: "center",
          justifyContent: "space-between",
     },
     subHead: {
          width: "100px",
          display: "flex",
          flexDirection: "row",
          alignItems: "center",
          justifyContent: "space-between",
     },

     commonText: {
          display: "flex",
          flexDirection: "row",
          alignItems: "center",
          justifyContent: "space-around",
     },
     fontMargin: {
          margin: "0px 5px",
     },
     spinBtn: {
          width: "200px",
          background: "hsl(60, 100%, 50%)",
          borderRadius: "12px",
          border: "none",
          padding: "0",
          cursor: "pointer",
          outlineOffset: "4px",
          marginTop: "50px",
     },
     spinBtn2: {
          display: "block",
          padding: "8px 42px",
          borderRadius: "12px",
          fontSize: "1.25rem",
          background: "hsl(62, 80%, 47%)",
          color: "#000",
          transform: "translateY(-15px)",
     },
     detailsDiv: {
          height: "70px",
          display: "flex",
          flexDirection: "column",
          alignItems: "center",
          justifyContent: "space-around",
     },
};
